[console]
# doesn't use base_config
level = "INFO"

[base_config]
level = "INFO"
rotation = "3 MB"
compression = "zip"


[endpoints]
# messages fron aiogram lib
file = "endpoints.log"
level = "DEBUG"

[config]
file = "config.log"
level = "INFO"

[alembic]
# log migrations
file = "alembic.log"

[all]
# collect all log messages.
level = "INFO"
file = "all.log"
