"""add_shortlinks

Revision ID: 5a0036016d9a
Revises: 
Create Date: 2024-01-25 18:03:06.282592

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0036016d9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'short_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('link_id', sa.String(), nullable=False),
        sa.Column('full_link', sa.String(), nullable=True),
        sa.Column('created_by_ip', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('counter', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__short_links')),
    )
    op.create_index(op.f('ix__short_links_link_id'), 'short_links', ['link_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__short_links_link_id'), table_name='short_links')
    op.drop_table('short_links')
    # ### end Alembic commands ###
