"""rename_url_field

Revision ID: 40b793832968
Revises: f5465644a82d
Create Date: 2024-01-26 10:42:45.656511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b793832968'
down_revision = 'f5465644a82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_links', column_name='full_link', new_column_name='url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_links', column_name='url', new_column_name='full_link')
    # ### end Alembic commands ###
