"""add_status_code

Revision ID: f5465644a82d
Revises: 5a0036016d9a
Create Date: 2024-01-25 19:56:37.038274

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5465644a82d"
down_revision = "5a0036016d9a"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("short_links", sa.Column("status_code", sa.Integer(), nullable=False))
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("short_links", "status_code")
  # ### end Alembic commands ###
